# -*- coding: utf-8 -*-
"""480_OOP_9ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cqlKYlvsrmTAYtw8SzwZi8HGyPjEPN9D
"""

class Professor:
  def __init__(self, name, age, course):
        self.name = name
        self.age = age
        self.course = course
  def greet_students(self):
        print("Welcome to class!")

# Write your code below:
class ISMProfessor(Professor):
   #define instance attribute
  def __init__(self, name, age, course):
    Professor.__init__(self, name, age, course)
   #def greet_students method
  def greet_students(self):
    print("Hi everyone! It's a great day to study ISM 480!")
    Professor.greet_students(self)

my_ism_professor = ISMProfessor("Bo",  34, "ISM 480")
my_ism_professor.greet_students()