# -*- coding: utf-8 -*-
"""480_OOP_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14UNYqphCujGxjT08Jx2RmqG9LPH1VEzv
"""

class Vehicle:

    def __init__(self, color, speed, fuel_type):
        self.color = color
        self.speed = speed  # In Km/h
        self.fuel_type = fuel_type

# Write your code below:

#Define the child class car
class Car(Vehicle):
    def __init__(self, color, speed, fuel_type, num_doors, is_electric):
      Vehicle.__init__(self, color, speed, fuel_type)
      self.num_doors = num_doors
      self.is_electric = is_electric

#create an instance of car
my_car = Car('red', 250, 'gas', 4, False)

#Print the attributes of my_car
print('Here is info about my car:')
print(f'Color: {my_car.color}')
print(f'Speed: {my_car.speed} Km/h')
print(f'Fuel Type: {my_car.fuel_type}')
print(f'Number of doors: {my_car.num_doors}')
if my_car.is_electric:
  print(f'Is electric: yes')
else:
  print(f'Is electric: no')