# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gEWrNJ4oHcGqe8G4KmdzgWLZoJnJS5EU
"""

import classes
my_ism_professor = classes.ISMProfessor("Bo", 35, "ISM480")
my_ism_professor.greet_students()